Repository voiceflow/google-runtime, pull requests merged in 2021-08, with the labels that each got.

#121 feat: add `last_utterance` global variable (VF-1162)
  lib/constants/flags.ts
  lib/services/google/request/index.ts
  tests/lib/services/google/request/index.unit.ts
Labels: ready to merge

#124 fix: google sheets val to num (VF-1169)
  package.json
  yarn.lock
Labels: ready to merge

#126 feat: better support for big JSON (VF-1399)
  backend/constants.ts
  backend/expressMiddleware.ts
  config.ts
  types.ts
Labels: ready for review

#127 fix: set default timeout time to 10s (VF-1549)
  config.ts
Labels: ready for review

#130 chore: remove ingest
  lib/clients/analytics.ts
Labels: ready to merge, autorebase:opt-in

#131 fix: cleanup logs (VF-1476)
  backend/expressMiddleware.ts
  lib/clients/analytics.ts
  lib/controllers/google.ts
  lib/services/adapter/index.ts
  package.json
  server.ts
  start.ts
  yarn.lock
Labels: ready for review, autorebase:opt-in
